const wordData = [
{word: "abandon", definition: "to give up; to leave behind"},
{word: "abolitionist", definition: "person who sought the end of slavery in the early and mid-1800s in the Unites States"},
{word: "academy", definition: "a school or college for special training"},
{word: "access", definition: "a way into something or someplace"},
{word: "accumulate", definition: "to build up or collect"},
{word: "acquire", definition: "to get possession or control of"},
{word: "adapt", definition: "to change in response to a new set of conditions"},
{word: "adjust", definition: "to become more suited to new conditions"},
{word: "administer", definition: "to manage; to direct"},
{word: "administrate", definition: "to carry out"},
{word: "advocate", definition: "supporter"},
{word: "aid", definition: "to help"},
{word: "alien", definition: "a person living in a country who is not a citizen of that country"},
{word: "allay", definition: "to reduce in strength"},
{word: "alliance", definition: "a partnership; a system in which countries agree to defend each other or to advance common causes"},
{word: "alter", definition: "to change"},
{word: "ambush", definition: "an attack in which the attacker hides and surprises the enemy"},
{word: "amend", definition: "to change or revise"},
{word: "amendment", definition: "a change, correction, or improvement added to a document"},
{word: "amnesty", definition: "the granting of a pardon to a large number of persons"},
{word: "animosity", definition: "hostility; ill will; hatred"},
{word: "annex", definition: "to add a territory to one's own territory"},
{word: "apprentice", definition: "a person who learns a trade from a skilled craftsperson"},
{word: "approach", definition: "to get closer to something"},
{word: "archaeology", definition: "the study of material remains of ancient peoples"},
{word: "armada", definition: "a fleet of warships"},
{word: "arsenal", definition: "a place to store weapons and military equipment"},
{word: "artifact", definition: "a tool, weapon, or other object left behind by early peoples"},
{word: "astrolabe", definition: "an instrument used to plan a course, using the stars"},
{word: "author", definition: "writer of books, articles, or other works"},
{word: "authority", definition: "the power to influence or command thought, opinion, or behavior"},
{word: "barricade", definition: "to block off"},
{word: "bicameral", definition: "having two separate lawmaking chambers"},
{word: "black codes", definition: "the laws passed in the South just after the Civil War aimed at controlling freed men and women and allowing plantation owners to take advantage of African American workers"},
{word: "blockade", definition: "actions that keep a country from communicating and trading with other nations"},
{word: "bond", definition: "a certificate that promises to repay borrowed money plus interest by a certain date"},
{word: "boomtown", definition: "a fast-growing community"},
{word: "border ruffian", definition: "armed supporter of slavery who crossed the border from Missouri to vote in Kansas during the mid-1850s"},
{word: "border state", definition: "state between the North and South that was divided over whether to remain in the Union or join the Confederacy: Delaware, Maryland, Kentucky, and Missouri"},
{word: "bounty", definition: "reward or payment"},
{word: "boycott", definition: "to refuse to buy items in order to show disapproval or force acceptance of one’s terms"},
{word: "brief", definition: "short"},
{word: "bureaucracy", definition: "a part of government in which specialized tasks are carried out by appointed officials rather than by elected ones; a part of government marked by lots of rules and regulation"},
{word: "burgess", definition: "elected representative to an assembly"},
{word: "cabinet", definition: "a group of advisers to a president"},
{word: "canal", definition: "an artificial waterway"},
{word: "capable", definition: "skillful"},
{word: "cape", definition: "a point of land that sticks out into water, much like a peninsula"},
{word: "capital", definition: "money or other resources used to create wealth"},
{word: "carbon dating", definition: "a scientific method of determining the age of an artifact"},
{word: "cash crop", definition: "a crop raised for sale in market"},
{word: "casualty", definition: "a soldier who is killed, wounded, captured, or missing in battle"},
{word: "caucus", definition: "a meeting of members of a political party to choose candidates for upcoming elections"},
{word: "cede", definition: "to transfer control of something"},
{word: "census", definition: "the official count of a population"},
{word: "channel", definition: "a long, narrow gutter or groove"},
{word: "charter", definition: "a document granting the holder the right to settle a colony"},
{word: "checks and balances", definition: "a system by which each branch of government limits the powers of other branches so that one branch does not become too powerful"},
{word: "circumnavigate", definition: "to travel completely around something"},
{word: "civic virtue", definition: "the democratic ideas, practices, and values that are at the heart of citizenship in a free society"},
{word: "civil disobedience", definition: "refusing to obey laws considered unjust as a nonviolent way to push for change"},
{word: "civil war", definition: "conflict between citizens of the same country"},
{word: "civilization", definition: "highly developed society"},
{word: "clan", definition: "a group of people who have a common ancestor"},
{word: "classical", definition: "related to the culture of ancient Greece and Rome"},
{word: "clause", definition: "a special condition in a formal document"},
{word: "clipper ship", definition: "a fast ship with sleek hulls and tall sails that “clipped” time from long journeys"},
{word: "coeducation", definition: "the teaching of males and females together"},
{word: "commission", definition: "a group of officials chosen for a specific responsibility"},
{word: "committee of correspondence", definition: "an organization that spread political ideas and information through the colonies"},
{word: "community", definition: "group of people who live in the same area"},
{word: "compass", definition: "an instrument that shows the direction of magnetic north"},
{word: "complex", definition: "highly detailed"},
{word: "compromise", definition: "a settlement of a dispute or disagreement reached by each side giving up some of what it wants in order to reach an agreement"},
{word: "concurrence", definition: "agreement"},
{word: "concurrent power", definition: "power shared by the states and federal government"},
{word: "conquistador", definition: "Spanish explorer in the Americas during the 1500s"},
{word: "consequence", definition: "effect or result of"},
{word: "constitution", definition: "detailed written plan for a government; a list of basic laws that support a government"},
{word: "contact", definition: "when two or more groups or objects come together"},
{word: "contradict", definition: "to go against or state the opposite"},
{word: "contrast", definition: "to compare in terms of differences"},
{word: "convention", definition: "a formal or official meeting"},
{word: "convert", definition: "to change from one belief, form, or use to another"},
{word: "corruption", definition: "dishonest or illegal actions"},
{word: "cotton gin", definition: "a machine that removes seeds from cotton fiber"},
{word: "credit", definition: "a loan, or the ability to pay for a good or service at a future time rather than at the time of purchase"},
{word: "Crusade", definition: "one of a series of expeditions Europeans made to regain control of Christian holy sites in the Middle East from the A.D.1000s to the 1200s"},
{word: "culture", definition: "a people’s shared values, beliefs, traditions, and behaviors"},
{word: "customs duty", definition: "a tax collected on goods that are imported"},
{word: "debate", definition: "a discussion of opposing points of view"},
{word: "debtor", definition: "person or country that owes money"},
{word: "decree", definition: "an order given by a person in authority"},
{word: "depreciate", definition: "to fall in value"},
{word: "depression", definition: "a period when economic activity slows and unemployment increases"},
{word: "desert", definition: "to leave without permission or intent to come back"},
{word: "devote", definition: "to commit oneself or one’s resources to something"},
{word: "diminish", definition: "to reduce, make smaller"},
{word: "discipline", definition: "the ability to follow rules and procedures"},
{word: "discrimination", definition: "unfair treatment based on prejudice against a certain group"},
{word: "distinct", definition: "clearly different from the others"},
{word: "distribute", definition: "to hand out, spread around"},
{word: "diversity", definition: "variety, such as of ethnic or national groups"},
{word: "domestic slave trade", definition: "the trade of enslaved people among states of the United States"},
{word: "dominate", definition: "to control"},
{word: "draft", definition: "a system of selecting people for required military service"},
{word: "dressing down", definition: "a serious punishment or scolding"},
{word: "due process", definition: "the legal rules and procedures established by law and guaranteed by the Constitution that the government must observe before depriving a person of life, liberty, or property"},
{word: "effigy", definition: "a mocking figure representing an unpopular individual"},
{word: "Electoral College", definition: "a group of people named by each state legislature to select the president and vice president"},
{word: "element", definition: "a part of a larger whole"},
{word: "elephantine", definition: "having great size"},
{word: "Emancipation Proclamation", definition: "the decree issued by President Abraham Lincoln freeing enslaved people in those parts of the Confederacy still in rebellion on January 1, 1863"},
{word: "embargo", definition: "a prohibition or blocking of trade with a certain country"},
{word: "emigrant", definition: "person who leaves his or her country to live somewhere else"},
{word: "emphasis", definition: "placing of stress or special importance on something"},
{word: "encounter", definition: "a sudden, often violent clash; to meet, come face-to-face with"},
{word: "enforce", definition: "to apply a rule or law; to carry out by force"},
{word: "enlist", definition: "to formally join a military force"},
{word: "entrench", definition: "to place within a trench, or ditch, for defense; to place in a strong defensive position"},
{word: "enumerated power", definition: "power specifically given Congress in the Constitution"},
{word: "epidemic", definition: "an illness that affects large numbers of people"},
{word: "equal protection", definition: "the equal application of the law regardless of a person’s race, religion, political beliefs, or other qualities"},
{word: "establish", definition: "to set up or create"},
{word: "estate", definition: "large area of land that has one owner"},
{word: "estimate", definition: "a rough calculation of a number"},
{word: "ethnic", definition: "of or relating to national, tribal, racial, religious, language, or cultural background"},
{word: "exclude", definition: "to prevent from being involved in something; to leave out"},
{word: "executive branch", definition: "branch of government that executes, or carries out, the law; headed by the president"},
{word: "expand", definition: "to increase in size or number"},
{word: "export", definition: "to sell goods to other countries; a good made in one country and then sold to another"},
{word: "facilitate", definition: "to help make happen"},
{word: "famine", definition: "an extreme shortage of food"},
{word: "favorite son", definition: "a candidate for national office who has support mostly from his home state"},
{word: "federal", definition: "relating to a national government"},
{word: "federalism", definition: "a form of government in which power is divided between the federal, or national, government and state government"},
{word: "federation", definition: "a government that links and unites different groups"},
{word: "flank", definition: "the side or edge of a military formation"},
{word: "forty-niner", definition: "fortune-seeker who came to California during the Gold Rush"},
{word: "found", definition: "to start, to establish"},
{word: "free enterprise", definition: "a type of economy where people and businesses are free to buy, sell, and produce whatever they want, with a minimum of government intervention"},
{word: "frigate", definition: "a fast, medium-sized warship"},
{word: "fugitive", definition: "person who is running away from legal authority"},
{word: "function", definition: "to be in action; to operate"},
{word: "goal", definition: "something one is trying to accomplish"},
{word: "grandfather clause", definition: "a device that allowed persons to vote if their fathers or grandfathers had voted before Reconstruction began"},
{word: "habeas corpus", definition: "court order that requires police to bring a prisoner to court to explain why they are holding the person"},
{word: "headright", definition: "a grant of land given to colonial settlers who paid their own way"},
{word: "heyday", definition: "the peak of one's strength"},
{word: "hieroglyphics", definition: "a form of writing that uses symbols or pictures to represent things, ideas, and sounds"},
{word: "hinder", definition: "to prevent"},
{word: "hindrance", definition: "an obstacle or impediment that prevents progress or achievement"},
{word: "immigrant", definition: "a person who comes to live permanently in a foreign country"},
{word: "impeach", definition: "to charge a public official with wrongdoing in office"},
{word: "implied powers", definition: "powers not specifically mentioned in the Constitution, but inferred from it"},
{word: "import", definition: "to bring goods or services into a country from abroad for sale"},
{word: "inauguration", definition: "a ceremony in which a president officially takes the oath of office"},
{word: "joint occupation", definition: "the control and settlement of an area by two or more countries or groups"},
{word: "joint-stock company", definition: "a company in which investors buy stock in return for a share of the company's future profits"},
{word: "judicial branch", definition: "the branch of government that interprets the law; it includes courts that settle disputes and questions of the law"},
{word: "judicial review", definition: "power of the Supreme Court to say whether any federal, state, or local law or government action goes against the Constitution"},
{word: "jurisdiction", definition: "a court’s power or right to hear and decide cases"},
{word: "justify", definition: "to provide an explanation for; to find reasons to support"},
{word: "legislative branch", definition: "the branch of government that makes laws"},
{word: "liberty", definition: "the state of being free within society from oppressive restrictions imposed by authority on one's way of life, behavior, or political views"},
{word: "lecture", definition: "speech meant to provide information, similar to what a teacher presents"},
{word: "legal", definition: "permitted by law"},
{word: "legislative branch", definition: "lawmaking branch of government"},
{word: "license", definition: "to give official authority to do something"},
{word: "limited government", definition: "idea that a government may only use the powers given to it by the people"},
{word: "link", definition: "to connect to"},
{word: "literacy", definition: "the ability to read and write"},
{word: "literacy test", definition: "a method used to prevent African Americans from voting by requiring prospective voters to read and write at a specified level"},
{word: "lock", definition: "in a canal, separate compartment with gates at each end used in which water levels rise and fall in order to raise or lower boats"},
{word: "Loyalist", definition: "an American colonist who remained loyal to Britain and opposed the war for independence"},
{word: "lynching", definition: "putting to death by the illegal action of a mob"},
{word: "magnanimous", definition: "noble, generous"},
{word: "maintain", definition: "to keep or uphold"},
{word: "maize", definition: "a variety of corn"},
{word: "majority", definition: "a number that is more than 50 percent of the total"},
{word: "Manifest Destiny", definition: "the belief popular in the United States during the 1800s that the country must extend its boundaries to the Pacific Ocean"},
{word: "manumission", definition: "the freeing of individual enslaved persons"},
{word: "martyr", definition: "a person who sacrifices his or her life for a principle or cause"},
{word: "medical", definition: "relating to medicine; help given to people who are sick or injured"},
{word: "mercantilism", definition: "an economic theory that a nation’s power depends on its ability to increase wealth by increasing exports and receiving precious metals"},
{word: "mercenary", definition: "paid soldier who serves in the armed forces of a foreign country"},
{word: "migration", definition: "the movement of a large number of people into a new area"},
{word: "militia", definition: "a military force made of ordinary citizens who are trained to fight in emergencies"},
{word: "ministry", definition: "the office and duties of a religious leader"},
{word: "minuteman", definition: "a civilian during Revolutionary era who was ready to fight with only one minute’s notice"},
{word: "mission", definition: "a religious community where farming was carried out and Native Americans were converted to Christianity"},
{word: "monopoly", definition: "a market where there is only one provider of a good or service"},
{word: "Morse code", definition: "a system for sending messages that uses a series of dots and dashes to represent letters of the alphabet, numbers, and punctuation"},
{word: "mosque", definition: "a Muslim house of worship"},
{word: "mountain man", definition: "an adventurer of the American West"},
{word: "mudslinging", definition: "a method in election campaigns that uses gossip and lies to make an opponent look bad"},
{word: "nationalism", definition: "a strong sense of devotion to one’s country"},
{word: "nativist", definition: "person opposed to immigration"},
{word: "naturalization", definition: "the process of becoming a citizen of another country"},
{word: "network", definition: "interconnected system"},
{word: "neutral", definition: "taking no side"},
{word: "neutral rights", definition: "privileges or freedoms that are granted to nations that do not choose a side in a conflict"},
{word: "nomad", definition: "a person who moves from place to place"},
{word: "nominating convention", definition: "a meeting in which representative members of a political party choose candidates to run for important elected offices"},
{word: "normal school", definition: "state-supported school for training high school graduates to become teachers"},
{word: "Northwest Passage", definition: "a sea route between the Atlantic and Pacific oceans, located along the north coast of North America"},
{word: "nullify", definition: "to legally overturn; to cancel"},
{word: "pacifists", definition: "people opposed to the use of war or violence to settle disputes"},
{word: "participate", definition: "to take part in"},
{word: "partisan", definition: "firmly favoring one party or faction"},
{word: "patent", definition: "sole legal right to an invention and its profits"},
{word: "Patriot", definition: "American colonist who favored American independence"},
{word: "patroon", definition: "landowner in the Dutch colonies who ruled over large areas of land"},
{word: "persecute", definition: "to mistreat peoples or groups on the basis of their beliefs"},
{word: "petition", definition: "a formal request for government action"},
{word: "pilgrimage", definition: "a journey to a holy place"},
{word: "plantation", definition: "a large farm"},
{word: "plurality", definition: "the largest number of something, but less than a majority"},
{word: "plus", definition: "in addition to"},
{word: "policy", definition: "a statement of ideals or plan of action"},
{word: "poll tax", definition: "a tax a person must pay in order to vote"},
{word: "popular sovereignty", definition: "the belief that government is subject to the will of the people"},
{word: "pose", definition: "to present; to offer"},
{word: "prairie schooner", definition: "a canvas-covered wagon used by pioneers in the mid-1800s"},
{word: "preamble", definition: "the introduction to a formal document that often tells why the document was written"},
{word: "precedent", definition: "something done or said that becomes an example for others to follow"},
{word: "prejudice", definition: "an unfair opinion not based on facts"},
{word: "presidio", definition: "a fort"},
{word: "previous", definition: "earlier"},
{word: "principal", definition: "most important"},
{word: "principle", definition: "a fundamental, or basic, law or idea"},
{word: "privateer", definition: "privately owned ship outfitted with weapons"},
{word: "process", definition: "to prepare"},
{word: "prodigal", definition: "wasteful"},
{word: "prodigious", definition: "large in size or quantity"},
{word: "productivity", definition: "a measure of how much a worker can produce within a given amount of time and effort"},
{word: "profane", definition: "not religious"},
{word: "proffered", definition: "present for acceptance"},
{word: "prohibit", definition: "to prevent or forbid"},
{word: "propaganda", definition: "ideas or information intentionally spread to harm or help a cause"},
{word: "proportional", definition: "having the proper size in relation to other objects or items"},
{word: "Protestantism", definition: "a form of Christianity that was in opposition to the Catholic Church"},
{word: "pueblo", definition: "a communal Native American structure; a town in Spanish-ruled lands"},
{word: "purchase", definition: "the act of buying something"},
{word: "pursue", definition: "to proceed with"},
{word: "radical", definition: "extreme"},
{word: "ranchero", definition: "a Mexican ranch owner"},
{word: "rancho", definition: "ranch, especially the large estates set up by Mexicans in the American West"},
{word: "ratify", definition: "to vote approval of"},
{word: "react", definition: "to act in response to something"},
{word: "rebellion", definition: "open defiance of authority"},
{word: "reconciliation", definition: "settlement, understanding"},
{word: "Reconstruction", definition: "the period of rebuilding the South after the Civil War and readmitting the former Confederate states into the Union"},
{word: "recruit", definition: "to enlist in the military"},
{word: "Reformation", definition: "a sixteenth-century religious movement rejecting or changing some Roman Catholic teachings and practices and establishing the Protestant churches"},
{word: "reformation", definition: "change"},
{word: "region", definition: "an area defined by a feature or characteristic"},
{word: "regulate", definition: "to control or govern"},
{word: "reinforce", definition: "to make stronger"},
{word: "reject", definition: "to refuse to accept"},
{word: "relinquish", definition: "to give up"},
{word: "relocate", definition: "to move to another place"},
{word: "rely", definition: "to depend upon"},
{word: "remove", definition: "to take away"},
{word: "Renaissance", definition: "a reawakening of culture and intellectual curiosity in Europe from the 1300s to the 1600s"},
{word: "renounce", definition: "to give up, to abandon"},
{word: "repeal", definition: "to cancel an act or law"},
{word: "representative government", definition: "a system in which citizens elect a smaller group to make laws andconduct government on their behalf"},
{word: "republic", definition: "a government in which citizens rule through elected representatives"},
{word: "reserved power", definition: "authority belonging only to the states"},
{word: "reside", definition: "to exist or live in"},
{word: "resistance", definition: "refusal to give in"},
{word: "resolution", definition: "an official expression of opinion by a group"},
{word: "resolve", definition: "to find a solution; to settle a conflict"},
{word: "resource", definition: "something that can be used for benefit, especially land, minerals, and water"},
{word: "restriction", definition: "rule or regulation that limits something"},
{word: "reveal", definition: "to show"},
{word: "revenue", definition: "incoming money from taxes or other sources"},
{word: "revere", definition: "to deeply love and respect"},
{word: "reverse", definition: "to go in the opposite direction"},
{word: "revival", definition: "religious meeting"},
{word: "rigid", definition: "firm and inflexible"},
{word: "route", definition: "line of travel"},
{word: "scalawag", definition: "a name given by former Confederates to Southern whites who supported Republican Reconstruction of the South"},
{word: "secede", definition: "to withdraw or break away from a nation or organization; to officially leave an organization"},
{word: "secession", definition: "withdrawal; to leave the Union"},
{word: "sectionalism", definition: "rivalry based on the special interests of different areas"},
{word: "sedition", definition: "activities aimed at weakening the established government by inciting resistance or rebellion to authority"},
{word: "segregation", definition: "the separation or isolation of a race, class, or group"},
{word: "separation of powers", definition: "the division of authority among executive, legislative, and judicial branches to make sure no one branch has too much power"},
{word: "series", definition: "events that occur one after the other"},
{word: "sharecropping", definition: "system of farming in which a farmer works land for an owner who provides equipment and seeds and receives a share of the crop"},
{word: "siege", definition: "an attempt to force surrender by blocking the movement of people or goods into or out of a place"},
{word: "similar", definition: "sharing qualities, but not the same as; like"},
{word: "slave codes", definition: "rules focusing on the behavior and punishment of enslaved people; laws in Southern states that controlled enslaved people"},
{word: "so-called", definition: "known as"},
{word: "source", definition: "a supply"},
{word: "sovereign", definition: "one who holds power"},
{word: "spiritual", definition: "an African American religious folk song"},
{word: "spoils system", definition: "practice of rewarding government jobs to political supporters; replacing government employees with the winning candidate’s supporters"},
{word: "states’ rights", definition: "the idea that states should have all powers that the Constitution does not give to the federal government or forbid to the states; theory that individual states are independent and have the right to control their most important affairs"},
{word: "status", definition: "rank or place as compared to others"},
{word: "stock", definition: "livestock"},
{word: "stoicism", definition: "the quality of not reacting to pleasure or pain"},
{word: "strait", definition: "a narrow water passage between larger bodies of water"},
{word: "strategy", definition: "a plan of action; a careful plan or method"},
{word: "strike", definition: "a work stoppage by employees as a protest against an employer"},
{word: "structure", definition: "a building"},
{word: "subjugate", definition: "conquer"},
{word: "subsistence farming", definition: "producing just enough to meet immediate needs"},
{word: "substitute", definition: "an alternate or replacement"},
{word: "suffrage", definition: "the right to vote"},
{word: "survive", definition: "to continue existing or living after nearly being destroyed"},
{word: "suspend", definition: "to temporarily set aside or stop operation of something"},
{word: "sustain", definition: "to suffer or experience"},
{word: "symbol", definition: "a word or object that stands for something else"},
{word: "technology", definition: "the use of scientific knowledge for practical purposes"},
{word: "tedious", definition: "boring"},
{word: "Tejano", definition: "a Texan of Latin American, often Mexican, descent"},
{word: "telegraph", definition: "a device that used electric signals to send messages"},
{word: "temperance", definition: "drinking little or no alcohol"},
{word: "tenant farmer", definition: "a farmer who pays a landowner an annual rent and worked for that person for a fixed number of days each year"},
{word: "terrace", definition: "a broad platform of flat land cut into a slope"},
{word: "theocracy", definition: "a society that is ruled by religious leaders"},
{word: "tidings", definition: "news"},
{word: "tolerance", definition: "the ability to accept and respect different views or behaviors"},
{word: "topic", definition: "subject of discussion"},
{word: "torrent", definition: "fast-moving liquid"},
{word: "total war", definition: "a strategy of bringing war to the entire society, not just the military"},
{word: "trade union", definition: "group of workers with the same trade, or skill"},
{word: "tradition", definition: "longstanding cultural belief or practice"},
{word: "transfer", definition: "to move"},
{word: "transform", definition: "to change significantly"},
{word: "triangular trade", definition: "pattern of trade that developed in colonial times among the Americas, Africa, and Europe"},
{word: "tributary", definition: "stream or smaller river that feeds into a larger river"},
{word: "tribute", definition: "money paid to a leader or state for protection"},
{word: "turnpike", definition: "road on which tolls are collected"},
{word: "underestimate", definition: "to judge something below its actual value"},
{word: "Underground Railroad", definition: "a system of cooperation to aid and house enslaved people who had escaped"},
{word: "uniform", definition: "of the same form with others"},
{word: "unimpaired", definition: "not harmed, not damaged"},
{word: "usurpation", definition: "an unjust seizing of power"},
{word: "utopia", definition: "community based on a vision of the perfect society"},
{word: "veto", definition: "to reject a bill and prevent it from becoming law"},
{word: "victuals", definition: "food"},
{word: "vigilante", definition: "person who acts as police, judge, and jury without formal legal authority"},
{word: "violate", definition: "to disregard or go against"},
{word: "widespread", definition: "over a wide area"},
{word: "writ of assistance", definition: "court document allowing customs officers to enter any location to search for smuggled goods"},
{word: "yeoman", definition: "farmer who owns a small farm"}
];

function displayWords(words) {
  const wordListElement = document.getElementById("wordList");
  wordListElement.innerHTML = "";
  words.forEach(({ word, definition }) => {
    const wordElement = document.createElement("div");
    wordElement.innerHTML = `<b>${word}</b>: ${definition}`;

    wordListElement.appendChild(wordElement);
  });
}

displayWords(wordData);

function sortAlphabetically() {
  const sortedWords = [...wordData].sort((a, b) =>
    a.word.localeCompare(b.word)
  );
  displayWords(sortedWords);
}

function showAll() {
  displayWords(wordData);
}

function searchWords() {
  const searchInput = document.getElementById("search");
  const searchTerm = searchInput.value.toLowerCase();

  const matchedWords = wordData.filter(({ word }) =>
    word.toLowerCase().includes(searchTerm)
  );
  displayWords(matchedWords);
}

function filterByStartLetter() {
  const startWithSelect = document.getElementById("startWith");
  const startLetter = startWithSelect.value;

  const filteredWords = wordData.filter(({ word }) =>
    word.toLowerCase().startsWith(startLetter.toLowerCase())
  );
  displayWords(filteredWords);
}

document.getElementById("search").addEventListener("input", searchWords);
document
  .getElementById("startWith")
  .addEventListener("change", filterByStartLetter);

function addWordDefinitions() {
  const wordListInput = document.getElementById("wordListInput");
  const wordList = wordListInput.value.trim().toLowerCase().split("\n");

  const matchedWords = [];

  wordList.forEach((word) => {
    const trimmedWord = word.trim();
    if (trimmedWord !== "") {
      const matchedWord = wordData.find(
        (data) => data.word.toLowerCase() === trimmedWord
      );
      if (matchedWord && !matchedWords.some((word) => word.word === matchedWord.word)) {
        matchedWords.push(matchedWord);
      }
    }
  });

  displayWords(matchedWords);
  wordListInput.value = "";
}